### ISSUE TITLE
python重制版的脚本可以用于linux服务器吗

### ISSUE THREAD

**Issue by 2log2n** [mivinci/cqupt#4]
大佬你好，我现在使用的服务器并没有curl程序，我可以使用python版本的脚本访问校园网吗，为什么我登录成功后仍然无法访问公网呢

**Comment by 2log2n** [comment]
应该是我本身服务器的问题，晚上试的时候又ping的通了，感谢学长

**Comment by mivinci** [comment]
好的 🙃
